### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by stefanheine** [thenativeweb/assertthat#23]
my test:
```
  test('is an object.', done => {
    assert.that(compare).is.ofType('object');
    done();
  });
```  

results in the error:
```
    1) is an object.


  0 passing (12ms)
  1 failing

  1) compare is an object.:
     ReferenceError: regeneratorRuntime is not defined
      at node_modules/assertthat/dist/constraints/throwingAsync.js:9:34
      at throwing (node_modules/assertthat/dist/constraints/throwingAsync.js:75:4)
      at Object.assert.that (node_modules/assertthat/dist/assertThat.js:60:22)
      at Context.done (test/units/lib/compareTests.js:19:12)
```

this is node 8.1.2 with assertthat 0.10.1.

I have another module where a similar test works ok, so I'm confused on what's going wrong here (I have reinstalled node_modules already). googling for the error points to babel and babel-polyfill, but I don't understand this context. there is no babel in my modules. I know that assertthat got translated by babel, though, but I don't understand how that result would work differently in two different modules.

**Comment by goloroden** [comment]
Hi Stefan 😊 

Actually, I experienced this behavior this morning as well… 🤔 

I assume that this is due to the fact that the Babel presets introduce usage of this function, but apparently it does not include this function into the final distributable file.

We need to figure out why this happens, and find a fix for this… if you have any idea, please let us know 😊

**Comment by goloroden** [comment]
PS: I think this is related to [this](https://stackoverflow.com/questions/33527653/babel-6-regeneratorruntime-is-not-defined-with-async-await)…

**Comment by stefanheine** [comment]
thanks for looking into this (and confirming that it not me doing something wrong). :)
I found that question as well, but it doesn't ring a bell.
I'll wait for your solution. ;)

**Comment by jumo-sballing** [comment]
Same here. Tests are running fine with 0.9.0. After an update to 0.10.1 I get 'ReferenceError: regeneratorRuntime is not defined'.

**Comment by goloroden** [comment]
We need to look into this, how to handle this in the best possible way… it is currently not our top priority, so please give us a few days.

**Comment by goloroden** [comment]
@stefanheine @jumo-sballing Today we have released `assertthat@0.10.2`, which *should* fix this error. Could you please have another look at it, and let @grundhoeferj and me know whether this worked out for you?

**Comment by grundhoeferj** [comment]
@stefanheine @jumo-sballing It is possible that `assertthat@0.10.2` also does not work. Please try `assertthat@0.10.3` and give us a short feedback :-)

**Comment by stefanheine** [comment]
0.10.2 still showed the issue, but in 0.10.3 it disappeared. thanks for the fix!

**Comment by goloroden** [comment]
That's great news, thanks 😊

**Comment by jumo-sballing** [comment]
assertthat@0.10.3 works perfectly.
